apiVersion: v1
kind: Service
metadata:
  name: amazon-service
  labels:
    app: amazon-app
spec:
  selector:
    app: amazon-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
