apiVersion: v1
kind: Service
metadata:
  name: amazon-service
  namespace: aws-webapp
  labels:
    app: amazon-app
spec:
  selector:
    app: amazon-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30033
  type: NodePort
