apiVersion: v1
kind: Service
metadata:
  name: amazon-service
  labels:
    app: amazon-app
spec:
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30033
  selector:
    app: amazon-app
  type: NodePort
